import { useState } from 'react'
import { FileText, Download, RefreshCw, CheckCircle, Copy } from 'lucide-react'
import { MOCK_PATIENTS } from '../../data/mockData'

function exportCSV() {
  const headers = ['ID', 'Name', 'Age', 'Type', 'HbA1c (%)', 'TIR (%)', 'Risk', 'Score', 'Region']
  const rows = MOCK_PATIENTS.map(p => [
    p.id, p.name, p.age, p.type, p.hba1c, p.tir, p.risk, p.score, p.region,
  ])
  const csv = [headers, ...rows].map(r => r.join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `AETHER_Glyca_Patients_${new Date().toISOString().slice(0, 10)}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

function generateAndDownload() {
  const now = new Date()

  const report = `AETHER-GLYCA POPULATION HEALTH REPORT
Generated: ${now.toLocaleString('en-IN')}
Report Period: Last 30 Days
Generated By: AI Clinical Intelligence Platform
=====================================

EXECUTIVE SUMMARY
-----------------
Total Patients Monitored: 10,000
Critical Risk (immediate): 97 patients (1.0%)
High Risk (priority review): 843 patients (8.4%)
Medium Risk (routine follow-up): 3,241 patients (32.4%)
Low Risk (maintained): 5,819 patients (58.2%)

POPULATION HEALTH METRICS
--------------------------
Average HbA1c: 8.6% (Target: <7.0%)
Population Time-in-Range (TIR): 58.4% (Target: >70%)
Average Patient Age: 52 years
Diabetes Type Distribution: Type 2: 78%, Type 1: 12%, Prediabetes: 10%
Coverage Region: Tamil Nadu (Primary) + Pan India

CRITICAL PATIENTS - IMMEDIATE INTERVENTION REQUIRED
-----------------------------------------------------
1. Rajesh Pandian  | Age 67 | Type2 | HbA1c: 12.1% | TIR: 21% | Risk: 91 | Chennai
2. Murugan Selvam  | Age 58 | Type2 | HbA1c: 11.2% | TIR: 28% | Risk: 87 | Coimbatore
3. Sundari Mani    | Age 60 | Type1 | HbA1c: 9.4%  | TIR: 47% | Risk: 58 | Madurai
4. Kavitha Rajan   | Age 44 | Type2 | HbA1c: 9.1%  | TIR: 44% | Risk: 63 | Madurai
5. Senthil Kumar   | Age 62 | Type2 | HbA1c: 9.8%  | TIR: 42% | Risk: 61 | Chennai

REGIONAL TIME-IN-RANGE BREAKDOWN
----------------------------------
Coimbatore : 61% TIR | 1,820 patients
Chennai         : 54% TIR | 2,340 patients
Madurai         : 49% TIR | 1,650 patients
Coimbatore      : 63% TIR | 1,420 patients
Salem           : 57% TIR | 980 patients
Tirunelveli     : 52% TIR | 790 patients
Other TN        : 58% TIR | 1,000 patients

ICD-10 CLASSIFICATION SUMMARY
-------------------------------
E11.65  - Type 2 DM with hyperglycemia      : 843 patients
E11.9   - Type 2 DM without complications   : 5,819 patients
E10.65  - Type 1 DM with hyperglycemia      : 97 patients
E11.649 - Type 2 DM with hypoglycemia       : 312 patients
E11.641 - Type 2 DM with hypoglycemia coma  : 12 patients
R73.09  - Prediabetes / Impaired glucose    : 917 patients

AI-GENERATED INTERVENTION RECOMMENDATIONS
-------------------------------------------
IMMEDIATE (This Week):
1. Outreach to 97 critical patients — glucose above 300 mg/dL sustained
2. Medication review for 12 patients with hypoglycemic episodes
3. Emergency clinical escalation: Rajesh Pandian (HbA1c 12.1%)

SHORT TERM (This Month):
4. Population dietary campaign: Switch Ponni Rice to Mappillai Samba
   (Estimated TIR improvement: +4-6% population-wide)
5. Schedule 843 high-risk patients for clinic review within 14 days
6. Deploy diet advisor to 3,241 medium-risk patients via AETHER app

LONG TERM (This Quarter):
7. Expand Metabolic Twin training to all 10,000 patients
8. FHIR integration with 3 partner hospitals in Coimbatore and Chennai
9. Community health worker training in Madurai (lowest TIR region)

DIETARY INTELLIGENCE HIGHLIGHTS
---------------------------------
Most logged high-GI food: Ponni Rice (GI 72) — 6,840 patients
Best switch recommendation: Mappillai Samba (GI 55) — only 890 patients using
Highest compliance region: Coimbatore (63% TIR)
Lowest compliance region: Madurai (49% TIR)

---
AETHER-Glyca AI Clinical Intelligence Platform v1.0
Team AI Architect | Coimbatore, Tamil Nadu, India
MedAthon 2025 | Earth Summit Submission`

  const blob = new Blob([report], { type: 'text/plain' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `AETHER_Glyca_Report_${now.toISOString().slice(0, 10)}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

const LAST_7_DAYS = [
  { date:'2026-03-29', critical:2, high:3, medium:3, low:2, avgHba1c:9.2, avgTir:51 },
  { date:'2026-03-30', critical:2, high:3, medium:3, low:2, avgHba1c:9.1, avgTir:52 },
  { date:'2026-03-31', critical:2, high:3, medium:3, low:2, avgHba1c:9.1, avgTir:53 },
  { date:'2026-04-01', critical:2, high:3, medium:3, low:2, avgHba1c:9.0, avgTir:54 },
  { date:'2026-04-02', critical:2, high:3, medium:2, low:3, avgHba1c:8.9, avgTir:56 },
  { date:'2026-04-03', critical:2, high:3, medium:2, low:3, avgHba1c:8.9, avgTir:57 },
  { date:'2026-04-04', critical:2, high:3, medium:2, low:3, avgHba1c:8.8, avgTir:58 },
]

export default function ReportsPage() {
  const [generating, setGenerating] = useState(false)
  const [generated,  setGenerated]  = useState(false)
  const [copied,     setCopied]     = useState(false)
  const [csvDone,    setCsvDone]    = useState(false)

  const handleGenerate = () => {
    setGenerating(true)
    setGenerated(false)
    setTimeout(() => {
      generateAndDownload()
      setGenerating(false)
      setGenerated(true)
      setTimeout(() => setGenerated(false), 3000)
    }, 1500)
  }

  const handleCopy = () => {
    const now = new Date()
    // Build same text inline for clipboard
    const lines = [
      'AETHER-GLYCA POPULATION HEALTH REPORT',
      `Generated: ${now.toLocaleString('en-IN')}`,
      'Report Period: Last 30 Days',
      'Generated By: AI Clinical Intelligence Platform',
      '=====================================',
      '',
      'EXECUTIVE SUMMARY',
      '-----------------',
      'Total Patients Monitored: 10,000',
      'Critical Risk (immediate): 97 patients (1.0%)',
      'High Risk (priority review): 843 patients (8.4%)',
      'Medium Risk (routine follow-up): 3,241 patients (32.4%)',
      'Low Risk (maintained): 5,819 patients (58.2%)',
      '',
      'POPULATION HEALTH METRICS',
      '--------------------------',
      'Average HbA1c: 8.6% (Target: <7.0%)',
      'Population Time-in-Range (TIR): 58.4% (Target: >70%)',
      'Average Patient Age: 52 years',
      'Diabetes Type Distribution: Type 2: 78%, Type 1: 12%, Prediabetes: 10%',
      'Coverage Region: Tamil Nadu (Primary) + Pan India',
    ].join('\n')
    navigator.clipboard.writeText(lines).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  return (
    <div className="p-6 space-y-6 accent-clinician">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-text flex items-center gap-2">
            <FileText size={22} className="text-blue-l"/> Reports
          </h1>
          <p className="text-muted text-sm mt-0.5">Population health reports · Tamil Nadu</p>
        </div>
        <div className="flex gap-2">
          <button className="btn-ghost flex items-center gap-2" onClick={handleCopy}>
            {copied ? <><CheckCircle size={15}/> Copied!</> : <><Copy size={15}/> Copy</>}
          </button>
          <button
            className="btn-ghost flex items-center gap-2"
            onClick={() => { exportCSV(); setCsvDone(true); setTimeout(() => setCsvDone(false), 3000) }}
          >
            {csvDone ? <><CheckCircle size={15}/> Exported!</> : <><Download size={15}/> Export CSV</>}
          </button>
          <button
            className="btn-primary flex items-center gap-2"
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating
              ? <><RefreshCw size={15} className="animate-spin"/> Generating…</>
              : generated
              ? <><CheckCircle size={15}/> Downloaded!</>
              : <><Download size={15}/> Generate Report</>}
          </button>
        </div>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label:'Total Patients',  value: MOCK_PATIENTS.length,                               color:'text-text'     },
          { label:'Critical Risk',   value: MOCK_PATIENTS.filter(p=>p.risk==='critical').length, color:'text-danger'   },
          { label:'Avg HbA1c',       value: `${(MOCK_PATIENTS.reduce((s,p)=>s+p.hba1c,0)/MOCK_PATIENTS.length).toFixed(1)}%`, color:'text-gold' },
          { label:'Avg TIR',         value: `${(MOCK_PATIENTS.reduce((s,p)=>s+p.tir, 0)/MOCK_PATIENTS.length).toFixed(0)}%`, color:'text-teal' },
        ].map(s => (
          <div key={s.label} className="stat-card">
            <div className={`stat-value ${s.color}`}>{s.value}</div>
            <div className="stat-label">{s.label}</div>
          </div>
        ))}
      </div>

      {/* Last 7 days table */}
      <div className="card">
        <h2 className="font-semibold text-text mb-4">Last 7 Days — Population Snapshot</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border text-xs text-muted uppercase tracking-wide">
                <th className="text-left pb-2 font-medium">Date</th>
                <th className="text-center pb-2 font-medium text-danger">Critical</th>
                <th className="text-center pb-2 font-medium text-gold">High</th>
                <th className="text-center pb-2 font-medium text-blue-l">Medium</th>
                <th className="text-center pb-2 font-medium text-success">Low</th>
                <th className="text-center pb-2 font-medium">Avg HbA1c</th>
                <th className="text-center pb-2 font-medium">Avg TIR</th>
              </tr>
            </thead>
            <tbody>
              {LAST_7_DAYS.map((row, i) => (
                <tr key={row.date}
                  className={`border-b border-border/40 ${i === LAST_7_DAYS.length-1 ? 'font-semibold' : ''}`}>
                  <td className="py-2.5 text-text text-xs">
                    {new Date(row.date).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}
                    {i === LAST_7_DAYS.length-1 && <span className="ml-2 text-teal text-xs">(today)</span>}
                  </td>
                  <td className="py-2.5 text-center text-danger">{row.critical}</td>
                  <td className="py-2.5 text-center text-gold">{row.high}</td>
                  <td className="py-2.5 text-center text-blue-l">{row.medium}</td>
                  <td className="py-2.5 text-center text-success">{row.low}</td>
                  <td className="py-2.5 text-center text-text">{row.avgHba1c}%</td>
                  <td className="py-2.5 text-center text-teal">{row.avgTir}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Report preview — first 20 lines */}
      <div className="card">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-semibold text-text">Report Preview</h2>
          <span className="text-xs text-muted">First 20 lines · Click Generate to download full .txt</span>
        </div>
        <pre className="text-xs text-muted font-mono bg-surface border border-border rounded-lg p-4 overflow-x-auto leading-relaxed max-h-72 overflow-y-auto whitespace-pre">
{`AETHER-GLYCA POPULATION HEALTH REPORT
Generated: ${new Date().toLocaleString('en-IN')}
Report Period: Last 30 Days
Generated By: AI Clinical Intelligence Platform
=====================================

EXECUTIVE SUMMARY
-----------------
Total Patients Monitored: 10,000
Critical Risk (immediate): 97 patients (1.0%)
High Risk (priority review): 843 patients (8.4%)
Medium Risk (routine follow-up): 3,241 patients (32.4%)
Low Risk (maintained): 5,819 patients (58.2%)

POPULATION HEALTH METRICS
--------------------------
Average HbA1c: 8.6% (Target: <7.0%)
Population Time-in-Range (TIR): 58.4% (Target: >70%)
Average Patient Age: 52 years
Diabetes Type Distribution: Type 2: 78%, Type 1: 12%, Prediabetes: 10%
...
[Full report includes: Regional TIR Breakdown · ICD-10 Classification · AI Recommendations · Dietary Intelligence]`}
        </pre>
      </div>
    </div>
  )
}
